kind: ReplicationController
apiVersion: v1
metadata:
  name: sonar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      volumes:
      - name: sonar-volume
        hostPath:
          path: /Users/jan/Development/minikube/sonar/sonarqube
      - name: postgres-volume
        hostPath:
          path: /tmp/postgres
      containers:
      # - name: nginx
      #   image: nginx:alpine
      #   ports:
      #   - containerPort: 80
      - name: sonarqube
        image: sonarqube:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://localhost:5432/sonar
        volumeMounts:
        - mountPath: /opt/sonarqube/conf
          name: sonar-volume
          subPath: conf
        - mountPath: /opt/sonarqube/data
          name: sonar-volume
          subPath: data
        - mountPath: /opt/sonarqube/extensions
          name: sonar-volume
          subPath: extensions
        - mountPath: /opt/sonarqube/lib/bundled-plugins
          name: sonar-volume
          subPath: lib/bundled-plugins
      - name: postgres
        image: postgres:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: sonar
        - name: POSTGRES_PASSWORD
          value: sonar
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgres-volume