kind: ReplicationController
apiVersion: v1
metadata:
  name: sonar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      volumes:
      - name: sonar-volume
        hostPath:
          path: /data/sonar/sonarqube
      - name: pg-data
        hostPath:
          path: /data/sonar/postgres
      - name: sonar-nginx-config
        configMap:
          name: sonar-nginx-config
          items:
          - key: proxy.conf
            path: proxy.conf
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: sonar-nginx-config
          subPath: proxy.conf
      - name: sonarqube
        image: sonarqube:6.3
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://localhost:5432/sonar
        volumeMounts:
        - mountPath: /opt/sonarqube/conf
          name: sonar-volume
          subPath: conf
        - mountPath: /opt/sonarqube/data
          name: sonar-volume
          subPath: data
        - mountPath: /opt/sonarqube/extensions
          name: sonar-volume
          subPath: extensions
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: sonar
        - name: POSTGRES_PASSWORD
          value: sonar
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data