kind: Service
apiVersion: v1
metadata:
  name: sonar
spec:
  selector:
    app: sonar
  ports:
    - port: 80
      targetPort: 9000
      name: "http"
    - port: 5432
      targetPort: 5432
      name: "postgres"
  type: LoadBalancer